import { defineStore } from 'pinia';
import { ref, computed } from 'vue';

// Category and Package name translations (English -> Arabic)
const categoryTranslations = {
  'sport': 'رياضة',
  'sports': 'رياضة',
  'electronics': 'إلكترونيات',
  'clothing': 'ملابس',
  'food': 'طعام',
  'books': 'كتب',
  'furniture': 'أثاث',
  'toys': 'ألعاب',
  'beauty': 'جمال',
  'health': 'صحة',
  'automotive': 'سيارات',
  'home': 'منزل',
  'office': 'مكتب',
  'general': 'عام',
};

const packageTranslations = {
  'hot drink': 'المشروبات الساخنة',
  'hot drinks': 'المشروبات الساخنة',
  'cold drink': 'المشروبات الباردة',
  'cold drinks': 'المشروبات الباردة',
  'breakfast': 'فطور',
  'lunch': 'غداء',
  'dinner': 'عشاء',
  'snacks': 'وجبات خفيفة',
  'beverages': 'مشروبات',
  'office supplies': 'لوازم مكتبية',
  'stationery': 'قرطاسية',
  'general': 'عام',
};

// Function to translate category/package names
export const translateName = (name, type = 'category') => {
  if (!name) return name;
  const lang = localStorage.getItem('language') || 'ar';
  if (lang !== 'ar') return name;

  const translations = type === 'category' ? categoryTranslations : packageTranslations;
  const nameLower = name.toLowerCase().trim();

  // Direct match
  if (translations[nameLower]) {
    return translations[nameLower];
  }

  // Partial match (contains)
  for (const [en, ar] of Object.entries(translations)) {
    if (nameLower.includes(en) || en.includes(nameLower)) {
      return ar;
    }
  }

  return name; // Return original if no translation found
};

// Translation dictionary
export const translations = {
  ar: {
    // Common
    'back': 'رجوع',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'edit': 'تعديل',
    'delete': 'حذف',
    'search': 'بحث',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'نجح',
    'confirm': 'تأكيد',
    'close': 'إغلاق',
    'ok': 'موافق',
    'confirm_action': 'تأكيد العملية',
    'are_you_sure': 'هل أنت متأكد؟',
    'are_you_sure_you_want_to': 'هل أنت متأكد أنك تريد {action}؟',

    // Navbar
    'makateb_store': 'مكاتب ستور',
    'search_products': 'ابحث عن المنتجات...',
    'sign_in': 'تسجيل الدخول',
    'profile': 'الملف الشخصي',
    'orders': 'الطلبات',
    'settings': 'الإعدادات',
    'logout': 'تسجيل الخروج',
    'contact_support': 'اتصل بالدعم',
    'admin_menu': 'قائمة الإدارة',
    'wishlist': 'قائمة الأمنيات',
    'my_wishlist': 'قائمة الأمنيات الخاصة بي',
    'cart': 'السلة',
    'chat': 'الدردشة',
    'dark_mode': 'الوضع الليلي',
    'light_mode': 'الوضع النهاري',
    'language': 'اللغة',
    'admin': 'الإدارة',
    'support_chat': 'دردشة الدعم',
    'copyright': '© 2026 مكاتب ستور. جميع الحقوق محفوظة.',

    // Home/Dashboard
    'welcome_to_makateb_store': 'مرحباً بك في مكاتب ستور',
    'welcome_description': 'مرحباً بك في مكاتب ستور! كل ما يحتاجه مكتبك في مكان واحد.',
    'products': 'المنتجات',
    'packages': 'الباقات',
    'most_searched': 'الأكثر بحثاً',
    'view_all': 'عرض الكل',
    'add_to_cart': 'أضف إلى السلة',
    'add': 'أضف',
    'add_to_wishlist': 'أضف إلى قائمة الأمنيات',
    'out_of_stock': 'نفدت الكمية',
    'only_left': 'بقي فقط',
    'only_x_items_available': 'متوفر فقط {count} عنصر(ات) في المخزون',
    'product_out_of_stock_wishlist': 'هذا المنتج غير متوفر. يمكنك إضافته إلى قائمة الأمنيات ليتم إشعارك عند توافره.',
    'product_out_of_stock': 'هذا المنتج غير متوفر',
    'please_login_to_manage_wishlist': 'يرجى تسجيل الدخول لإدارة قائمة الأمنيات',
    'failed_to_clear_wishlist': 'فشل مسح قائمة الأمنيات',
    'no_items_in_stock_to_add_to_cart': 'لا توجد عناصر متوفرة في المخزون لإضافتها إلى السلة',
    'added_x_items_to_cart': 'تمت إضافة {count} عنصر(ات) إلى السلة',
    'some_items_could_not_be_added_to_cart': 'لم يتمكن من إضافة بعض العناصر إلى السلة',
    'wishlist_cleared': 'تم مسح قائمة الأمنيات',
    'failed_to_delete_product': 'فشل حذف المنتج',
    'please_login_to_update_cart_items': 'يرجى تسجيل الدخول لتحديث عناصر السلة',
    'please_login_to_remove_cart_items': 'يرجى تسجيل الدخول لإزالة عناصر السلة',
    'failed_to_load_package': 'فشل تحميل الباقة',
    'this_package_has_no_products': 'هذه الباقة لا تحتوي على منتجات',
    'please_select_an_image_file': 'يرجى اختيار ملف صورة',
    'please_login_to_contact_support': 'يرجى تسجيل الدخول للتواصل مع الدعم',
    'no_admins_available_at_the_moment': 'لا يوجد مشرفون متاحون في الوقت الحالي',
    'failed_to_connect_to_support': 'فشل الاتصال بالدعم. يرجى المحاولة مرة أخرى لاحقاً',
    'items': 'عناصر',
    'browse_products': 'تصفح المنتجات',
    'explore_curated_collection': 'استكشف مجموعتنا المختارة',

    // Product
    'product_details': 'تفاصيل المنتج',
    'back_to_products': 'رجوع إلى المنتجات',
    'category': 'الفئة',
    'select_category': 'اختر الفئة',
    'price': 'السعر',
    'description': 'الوصف',
    'quantity': 'الكمية',
    'stock': 'المخزون',
    'customer_reviews': 'تقييمات العملاء',
    'add_review': 'أضف تقييم',
    'rating': 'التقييم',
    'comment': 'تعليق',
    'submit': 'إرسال',

    // Package
    'package_details': 'تفاصيل الباقة',
    'back_to_packages': 'رجوع إلى الباقات',
    'special_package_deal': 'عرض باقة خاص',
    'save': 'وفر',
    'original_price': 'السعر الأصلي',
    'whats_included': 'ما المضمن',
    'add_package_to_cart': 'أضف الباقة إلى السلة',

    // Cart
    'shopping_cart': 'سلة التسوق',
    'empty_cart': 'سلة التسوق فارغة',
    'start_shopping': 'ابدأ التسوق',
    'total': 'المجموع',
    'checkout': 'الدفع',
    'remove': 'إزالة',
    'view_your_cart': 'عرض سلة التسوق',

    // Checkout
    'checkout_page': 'صفحة الدفع',
    'order_summary': 'ملخص الطلب',
    'subtotal': 'المجموع الفرعي',
    'service_fees': 'رسوم الخدمة',
    'payment_method': 'طريقة الدفع',
    'cash_on_delivery': 'الدفع عند الاستلام',
    'credit_card': 'بطاقة ائتمان',
    'complete_purchase': 'إتمام الشراء',
    'shipping_address': 'عنوان الشحن',
    'city': 'المدينة',
    'address': 'العنوان',
    'phone': 'الهاتف',

    // Orders
    'order_history': 'سجل الطلبات',
    'no_orders': 'لا توجد طلبات',
    'order_id': 'رقم الطلب',
    'order': 'طلب',
    'order_date': 'تاريخ الطلب',
    'status': 'الحالة',
    'pending': 'قيد الانتظار',
    'processing': 'قيد المعالجة',
    'shipped': 'تم الشحن',
    'delivered': 'تم التسليم',
    'cancelled': 'ملغي',
    'remove_order': 'إزالة الطلب',
    'confirm_remove_order': 'هل أنت متأكد من إزالة هذا الطلب من السجل الخاص بك؟',
    'order_removed_successfully': 'تمت إزالة الطلب بنجاح',
    'failed_to_remove_order': 'فشل إزالة الطلب',

    // Settings
    'settings': 'الإعدادات',
    'basic_information': 'المعلومات الأساسية',
    'first_name': 'الاسم الأول',
    'last_name': 'اسم العائلة',
    'email_address': 'عنوان البريد الإلكتروني',
    'save_changes': 'حفظ التغييرات',
    'saving': 'جاري الحفظ...',
    'change_password': 'تغيير كلمة المرور',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'confirm_password': 'تأكيد كلمة المرور',
    'changing': 'جاري التغيير...',
    'danger_zone': 'منطقة الخطر',
    'delete_account': 'حذف الحساب',
    'delete_account_warning': 'بمجرد حذف حسابك، لا يمكن التراجع. يرجى التأكد.',
    'are_you_sure': 'هل أنت متأكد تماماً؟',
    'yes_delete': 'نعم، احذف حسابي',
    'language': 'اللغة',
    'select_language': 'اختر اللغة',
    'arabic': 'العربية',
    'english': 'الإنجليزية',
    'account_required': 'حساب مطلوب',
    'account_required_for_orders_support': 'يجب إنشاء حساب لعرض سجل الطلبات أو التواصل مع الدعم',
    'continue_shopping': 'متابعة التسوق',

    // Profile
    'user_information': 'معلومات المستخدم',
    'edit_information': 'تعديل المعلومات',
    'phone': 'الهاتف',
    'location': 'الموقع',
    'bio': 'السيرة الذاتية',
    'privacy_settings': 'إعدادات الخصوصية',
    'profile_visibility': 'رؤية الملف الشخصي',
    'public': 'عام',
    'private': 'خاص',
    'not_provided': 'غير متوفر',
    'does_not_create_account': 'لم يقم بإنشاء حساب',
    'order_information': 'معلومات الطلب',

    // Chat
    'messages': 'الرسائل',
    'customer_chat': 'دردشة العملاء',
    'select_user': 'اختر مستخدماً لبدء الدردشة',
    'type_message': 'اكتب رسالتك...',
    'send': 'إرسال',
    'no_conversations': 'لا توجد محادثات',
    'are_you_sure_clear_chat': 'هل أنت متأكد من مسح هذه المحادثة؟',
    'please_select_image_file': 'يرجى اختيار ملف صورة',
    'please_enter_valid_url': 'يرجى إدخال رابط صحيح',
    'upload_to_cloudinary': 'رفع إلى Cloudinary',
    'select_file': 'اختر ملف',
    'drag_drop_or_click_to_upload_cloudinary': 'اسحب وأفلت أو انقر للرفع إلى Cloudinary',
    'image_link': 'رابط الصورة',
    'cloudinary': 'Cloudinary',
    'preview': 'معاينة',
    'failed_to_send_message': 'فشل إرسال الرسالة',
    'failed_to_fetch_conversations': 'فشل جلب المحادثات',
    'failed_to_fetch_messages': 'فشل جلب الرسائل',
    'failed_to_clear_chat': 'فشل مسح المحادثة',
    'chat_cleared_successfully': 'تم مسح المحادثة بنجاح!',
    'search_users': 'ابحث عن المستخدمين...',

    // Search
    'search_page': 'صفحة البحث',
    'filter': 'تصفية',
    'sort_by': 'ترتيب حسب',
    'price_range': 'نطاق السعر',
    'min': 'الحد الأدنى',
    'max': 'الحد الأقصى',
    'apply': 'تطبيق',
    'reset': 'إعادة تعيين',
    'no_products_found': 'لم يتم العثور على منتجات',
    'most_relevant': 'الأكثر صلة',
    'price_low_to_high': 'السعر: من الأقل إلى الأعلى',
    'price_high_to_low': 'السعر: من الأعلى إلى الأقل',
    'highest_rated': 'الأعلى تقييماً',
    'found': 'تم العثور على',
    'for': 'لـ',
    'try_adjusting_search': 'حاول تعديل البحث أو الفلاتر للعثور على ما تبحث عنه.',
    'clear_all_filters': 'مسح جميع الفلاتر',

    // Admin
    'manage_site': 'إدارة الموقع',
    'manage_users': 'إدارة المستخدمين',
    'manage_categories': 'إدارة الفئات',
    'manage_packages': 'إدارة الباقات',
    'manage_products': 'إدارة المنتجات',
    'products_in_category': 'المنتجات في الفئة',
    'add_products': 'إضافة منتجات',
    'no_products_available': 'لا توجد منتجات متاحة',
    'failed_to_add_product_to_category': 'فشلت إضافة المنتج إلى الفئة',
    'failed_to_remove_product_from_category': 'فشلت إزالة المنتج من الفئة',
    'service_fees': 'رسوم الخدمة',
    'blocked_users': 'المستخدمون المحظورون',
    'customer_chat': 'دردشة العملاء',
    'create_product': 'إنشاء منتج',
    'edit_product': 'تعديل منتج',
    'create_category': 'إنشاء فئة',
    'create_package': 'إنشاء باقة',
    'edit_package': 'تعديل الباقة',
    'product_name': 'اسم المنتج',
    'product_description': 'وصف المنتج',
    'product_price': 'سعر المنتج',
    'product_stock': 'المخزون',
    'product_category': 'فئة المنتج',
    'add_to_packages': 'إضافة إلى الباقات',
    'product_images': 'صور المنتج',
    'enter_image_url': 'أدخل رابط الصورة',
    'add_image': 'أضف صورة',

    // Login
    'welcome_back': 'مرحباً بعودتك',
    'sign_in_account': 'تسجيل الدخول إلى حسابك',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'role': 'الدور',
    'select_role': 'اختر الدور',
    'customer': 'عميل',
    'admin': 'مدير',
    'sign_in': 'تسجيل الدخول',
    'dont_have_account': 'ليس لديك حساب؟',
    'sign_up': 'سجل',
    'create_account': 'إنشاء حساب',
    'already_have_account': 'هل لديك حساب بالفعل؟',
    'card_number': 'رقم البطاقة',
    'expiry_date': 'تاريخ انتهاء الصلاحية',
    'cvv': 'رمز الأمان',
    'continue_as_guest': 'المتابعة كضيف',
    'please_login_to_access_settings': 'يرجى تسجيل الدخول للوصول إلى الإعدادات',
    'light_mode': 'الوضع الفاتح',
    'dark_mode': 'الوضع الداكن',
    'shop_now': 'تسوق الآن',
    'special_package_deals': 'عروض الباقات الخاصة',
    'categories': 'الفئات',
    'all': 'الكل',
    'all_products': 'جميع المنتجات',
    'no_search_data': 'لا توجد بيانات بحث متاحة بعد',
    'no_packages_available': 'لا توجد باقات متاحة',
    'no_products_found': 'لم يتم العثور على منتجات. جرب بحثاً أو فئة مختلفة.',
    'adding': 'جاري الإضافة...',
    'general': 'عام',
    'please_login_to_add_items': 'يرجى تسجيل الدخول لإضافة العناصر',
    'removed_from_wishlist': 'تمت الإزالة من قائمة الأمنيات',
    'added_to_wishlist': 'تمت الإضافة إلى قائمة الأمنيات',
    'added_to_cart': 'تمت الإضافة إلى السلة',
    'failed_to_add_to_cart': 'فشلت إضافة العنصر إلى السلة',
    'failed_to_update_wishlist': 'فشل تحديث قائمة الأمنيات',
    'package_added_to_cart': 'تمت إضافة الباقة إلى السلة',
    'failed_to_add_package_to_cart': 'فشلت إضافة الباقة إلى السلة',
    'uncategorized': 'غير مصنف',
    'reviews': 'تقييمات',
    'no_description_available': 'لا يوجد وصف متاح',
    'only_left_in_stock': 'بقي فقط',
    'left_in_stock': 'في المخزون',
    'add_package_to_cart': 'أضف الباقة إلى السلة',
    'whats_included': 'ما المضمن',
    'no_products_in_package': 'لا توجد منتجات في هذه الباقة',
    'your_cart_is_empty': 'سلة التسوق فارغة',
    'add_some_products': 'أضف بعض المنتجات الجميلة للبدء',
    'start_shopping': 'ابدأ التسوق',
    'order_summary': 'ملخص الطلب',
    'subtotal': 'المجموع الفرعي',
    'shipping': 'الشحن',
    'calculated_at_checkout': 'يتم حسابه عند الدفع',
    'proceed_to_checkout': 'المتابعة إلى الدفع',
    'remove': 'إزالة',
    'please_login_to_view_orders': 'يرجى تسجيل الدخول لعرض طلباتك',
    'start_shopping_and_orders': 'ابدأ التسوق وستظهر طلباتك هنا',
    'placed_on': 'تم الطلب في',
    'items_count': 'عناصر',
    'view_details': 'عرض التفاصيل',
    'contact_information': 'معلومات الاتصال',
    'full_name': 'الاسم الكامل',
    'shipping_address': 'عنوان الشحن',
    'zip_code': 'الرمز البريدي',
    'select_location': 'اختر الموقع',
    'payment_method': 'طريقة الدفع',
    'cash_on_delivery': 'الدفع عند الاستلام',
    'credit_card': 'بطاقة ائتمان',
    'complete_purchase': 'إتمام الشراء',
    'customer_chat': 'دردشة العملاء',
    'search_users': 'ابحث عن المستخدمين...',
    'select_user_to_chat': 'اختر مستخدماً لبدء الدردشة',
    'no_messages': 'لا توجد رسائل',
    'type_your_message': 'اكتب رسالتك...',
    'send': 'إرسال',
    'admin_code': 'رمز المدير',
    'enter_admin_code': 'أدخل رمز المدير',
    'manage_admin_codes': 'إدارة رموز المديرين',
    'create_manage_admin_codes_description': 'إنشاء وإدارة رموز المديرين',
    'add_new_admin_code': 'إضافة رمز مدير جديد',
    'code_must_be_4_digits': 'يجب أن يكون الرمز 4 أرقام',
    'adding': 'جاري الإضافة...',
    'add_code': 'إضافة الرمز',
    'admin_codes_list': 'قائمة رموز المديرين',
    'no_admin_codes': 'لا توجد رموز مديرين',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'super_admin': 'مدير رئيسي',
    'protected': 'محمي',
    'created_at': 'تاريخ الإنشاء',
    'deactivate': 'تعطيل',
    'activate': 'تفعيل',
    'are_you_sure_delete_admin_code': 'هل أنت متأكد من حذف رمز المدير هذا؟',
    'admin_code_added_successfully': 'تم إضافة رمز المدير بنجاح',
    'admin_code_deleted_successfully': 'تم حذف رمز المدير بنجاح',
    'admin_code_updated_successfully': 'تم تحديث رمز المدير بنجاح',
    'failed_to_fetch_admin_codes': 'فشل جلب رموز المديرين',
    'failed_to_add_admin_code': 'فشل إضافة رمز المدير',
    'failed_to_delete_admin_code': 'فشل حذف رمز المدير',
    'failed_to_update_admin_code': 'فشل تحديث رمز المدير',
    'cannot_delete_super_admin_code': 'لا يمكن حذف رمز المدير الرئيسي',
    'cannot_modify_super_admin_code': 'لا يمكن تعديل رمز المدير الرئيسي',
    'unauthorized_access': 'غير مصرح بالوصول',
    'enter_your_password': 'أدخل كلمة المرور',
    'name_example': 'name@example.com',
    'enter_full_name': 'أدخل اسمك الكامل',
    'no_reviews_yet': 'لا توجد تقييمات بعد. كن أول من يقيم هذا المنتج!',
    'write_review': 'اكتب تقييماً',
    'anonymous': 'مجهول',
    'your_review': 'تقييمك',
    'share_thoughts': 'شارك أفكارك حول هذا المنتج...',
    'submitting': 'جاري الإرسال...',
    'submit_review': 'إرسال التقييم',
    'please_login_to_review': 'يرجى تسجيل الدخول لإرسال تقييم',
    'review_submitted_successfully': 'تم إرسال التقييم بنجاح!',
    'failed_to_submit_review': 'فشل إرسال التقييم',
    'are_you_sure_delete_comment': 'هل أنت متأكد من حذف هذا التعليق؟',
    'failed_to_delete_comment': 'فشل حذف التعليق',
    'processing': 'جاري المعالجة...',
    'place_order': 'تأكيد الطلب',
    'agree_terms_conditions': 'بإتمام طلبك، أنت توافق على شروطنا وأحكامنا.',
    'quantity_label': 'الكمية',
    'loading_order_details': 'جاري تحميل تفاصيل الطلب...',
    'loading_products': 'جاري التحميل...',
    'loading_packages': 'جاري التحميل...',
    'loading_categories': 'جاري التحميل...',
    'order_status': 'حالة الطلب',
    'order_items': 'عناصر الطلب',
    'price_each': 'السعر: {price} دينار لكل',
    'in_stock_available': 'متوفر ({stock} متاح)',
    'out_of_stock': 'غير متوفر',
    'customer_information': 'معلومات العميل',
    'name': 'الاسم',
    'phone': 'الهاتف',
    'phone_number': 'رقم الهاتف',
    'tax': 'الضريبة',
    'free': 'مجاني',
    'my_profile': 'ملفي الشخصي',
    'private_account': 'حساب خاص',
    'private_account_description': 'عند التمكين، يمكنك فقط رؤية معلومات ملفك الشخصي.',
    'edit_profile': 'تعديل الملف الشخصي',
    'wishlist_empty': 'قائمة الأمنيات فارغة',
    'save_favorite_products': 'احفظ منتجاتك المفضلة في قائمة الأمنيات!',
    'move_to_cart': 'نقل إلى السلة',
    'adding_to_cart': 'جاري الإضافة إلى السلة...',
    'back_to_orders': 'العودة إلى الطلبات',
    'order_not_found': 'الطلب غير موجود',
    'no_items_in_order': 'لا توجد عناصر في هذا الطلب',
    'items_moved_to_cart': 'تم نقل {count} عنصر(ات) إلى السلة!',
    'items_moved_to_cart_wishlist': 'تم نقل {inStock} عنصر(ات) متوفر(ة) إلى السلة. تمت إضافة {outOfStock} عنصر(ات) غير متوفر(ة) إلى قائمة الأمنيات.',
    'all_items_out_of_stock': 'جميع العناصر غير متوفرة. تمت إضافة {count} عنصر(ات) إلى قائمة الأمنيات.',
    'no_items_could_be_moved': 'لا يمكن نقل أي عناصر إلى السلة.',
    'failed_to_move_to_cart': 'فشل نقل العناصر إلى السلة',
    'orders_checkout': 'الموافقة على الطلبات',
    'approve_or_reject_payments': 'الموافقة على أو رفض مدفوعات العملاء',
    'back_to_admin_dashboard': 'العودة إلى لوحة تحكم المدير',
    'pending': 'قيد الانتظار',
    'total_orders': 'إجمالي الطلبات',
    'approved': 'موافق عليه',
    'rejected': 'مرفوض',
    'guest_user': 'مستخدم ضيف',
    'hide': 'إخفاء',
    'view': 'عرض',
    'service_fee': 'رسوم الخدمة',
    'delivery_fee': 'رسوم التوصيل',
    'reject': 'رفض',
    'approve_payment': 'الموافقة على الدفع',
    'payment_approved': 'تمت الموافقة على الدفع',
    'payment_rejected': 'تم رفض الدفع',
    'no_orders_found': 'لم يتم العثور على طلبات',
    'no_orders_yet': 'لا توجد طلبات حتى الآن',
    'no_orders_with_status': 'لا توجد طلبات بحالة {status}',
    'are_you_sure_approve_payment': 'هل أنت متأكد من الموافقة على هذا الدفع؟',
    'are_you_sure_reject_payment': 'هل أنت متأكد من رفض هذا الدفع؟',
    'payment_approved_successfully': 'تمت الموافقة على الدفع بنجاح!',
    'failed_to_approve_payment': 'فشل الموافقة على الدفع',
    'failed_to_reject_payment': 'فشل رفض الدفع',
    'failed_to_fetch_orders': 'فشل جلب الطلبات',
    'failed_to_fetch_customers': 'فشل جلب العملاء',
    'failed_to_load_order_data': 'فشل تحميل بيانات الطلب',
    'failed_to_load_user_data': 'فشل تحميل بيانات المستخدم',
    'user_profile_updated_successfully': 'تم تحديث ملف المستخدم بنجاح',
    'failed_to_update_user_profile': 'فشل تحديث ملف المستخدم',
    'not_specified': 'غير محدد',
    'all_users': 'جميع المستخدمين',
    'active_pages': 'الصفحات النشطة',
    'showing_all_products': 'عرض جميع المنتجات ({count})',
    'total_registered_users': 'إجمالي المستخدمين المسجلين ({count})',
    'active_pages_count': 'عدد الصفحات النشطة ({count})',
    'blocked_users_count': 'عدد المستخدمين المحظورين ({count})',
    'details': 'التفاصيل',
    'stock': 'المخزون',
    'no_users_found': 'لم يتم العثور على مستخدمين',
    'no_pages_found': 'لم يتم العثور على صفحات',
    'no_blocked_users': 'لا يوجد مستخدمون محظورون',
    'all_users_active': 'جميع المستخدمين نشطون حالياً',
    'path': 'المسار',
    'last_visit': 'آخر زيارة',
    'total_visits': 'إجمالي الزيارات',
    'blocked_on': 'تم الحظر في',
    'unblock_user': 'إلغاء حظر المستخدم',
    'are_you_sure_unblock_user': 'هل أنت متأكد من إلغاء حظر هذا المستخدم؟',
    'user_unblocked_successfully': 'تم إلغاء حظر المستخدم بنجاح',
    'failed_to_unblock_user': 'فشل إلغاء حظر المستخدم',
    'user': 'مستخدم',
    'home_page': 'الصفحة الرئيسية',
    'products_page': 'صفحة المنتجات',
    'shopping_cart': 'سلة التسوق',
    'wishlist': 'قائمة الأمنيات',
    'checkout': 'الدفع',
    'profile_page': 'صفحة الملف الشخصي',
    'orders_history': 'سجل الطلبات',
    'settings': 'الإعدادات',
    'support_chat': 'دردشة الدعم',
    'search_results': 'نتائج البحث',
    'total_products': 'إجمالي المنتجات',
    'total_users': 'إجمالي المستخدمين',
    'active_packages': 'الباقات النشطة',
    'click_to_view_details': 'انقر لعرض التفاصيل',
    'back_to_home': 'العودة إلى الصفحة الرئيسية',
    'reorder': 'إعادة الطلب',
    'order_added_to_cart': 'تمت إضافة {count} عنصر(ات) إلى السلة!',
    'all_packages': 'جميع الباقات',
    'showing_all_packages': 'عرض جميع الباقات ({count})',
    'off': 'خصم',
    'welcome_admin_manage_store': 'مرحباً، المشرف! قم بإدارة جميع جوانب متجر مكاتب ستور.',
    'create_edit_packages_description': 'إنشاء وتعديل الباقات وإضافة/إزالة المنتجات',
    'create_categories_description': 'إنشاء الفئات وتنظيم المنتجات',
    'create_edit_products_description': 'إنشاء وتعديل المنتجات وإدارة المخزون',
    'view_block_manage_users_description': 'عرض وحظر وإدارة جميع المستخدمين',
    'set_delivery_service_fees_description': 'تعيين رسوم التوصيل والخدمة حسب الموقع',
    'view_manage_blocked_users_description': 'عرض وإدارة المستخدمين المحظورين',
    'chat_with_customers_realtime_description': 'الدردشة مع العملاء في الوقت الفعلي',
    'approve_reject_payments_description': 'الموافقة على أو رفض مدفوعات العملاء',
    'account_blocked': 'الحساب محظور',
    'account_blocked_message': 'عذراً، قام المشرف بحظر حسابك. لمعرفة السبب، اتصل بفريق الدعم',
    'contact_support_team': 'اتصل بفريق الدعم',
    'type_message': 'اكتب رسالة...',
    'loading_blocked_information': 'جاري تحميل معلومات الحظر...',
    'failed_to_send_message': 'فشل إرسال الرسالة',
    'block_list': 'قائمة المحظورين',
    'manage_blocked_users_description': 'إدارة المستخدمين الذين تم تقييدهم من المنصة',
    'search_by_name_or_email': 'البحث بالاسم أو البريد الإلكتروني...',
    'avatar': 'الصورة',
    'name': 'الاسم',
    'email': 'البريد الإلكتروني',
    'role': 'الدور',
    'date_blocked': 'تاريخ الحظر',
    'password': 'كلمة المرور',
    'stored_encrypted': 'مخزنة (مشفرة)',
    'not_available': 'غير متاحة',
    'blocked_information': 'معلومات الحظر',
    'blocked_date': 'تاريخ الحظر',
    'blocked_by': 'تم الحظر بواسطة',
    'note': 'ملاحظة',
    'blocked_user_note': 'تم حذف حساب هذا المستخدم. المعلومات المعروضة أعلاه من البيانات المؤرشفة. يمكنك إلغاء الحظر لاستعادة حسابه.',
    'action': 'الإجراء',
    'no_blocked_users_found': 'لم يتم العثور على مستخدمين محظورين',
    'unblock': 'إلغاء الحظر',
    'showing_results': 'عرض {from} إلى {to} من {total} نتيجة',
    'confirm_unblock_user': 'هل أنت متأكد من إلغاء حظر هذا المستخدم؟ سيتم استعادة حسابه وسيظهر في قائمة المستخدمين.',
    'user_unblocked_successfully': 'تم إلغاء حظر المستخدم واستعادة الحساب بنجاح',
    'failed_to_unblock_user': 'فشل إلغاء حظر المستخدم',
    'failed_to_fetch_blocked_users': 'فشل جلب المستخدمين المحظورين',
    'admin': 'مشرف',
    'customer': 'عميل',
    'please_enter_first_name': 'الرجاء إدخال الاسم الأول على الأقل',
    'basic_information_updated_successfully': 'تم تحديث المعلومات الأساسية بنجاح!',
    'failed_to_update_profile': 'فشل تحديث الملف الشخصي',
    'passwords_do_not_match': 'كلمات المرور الجديدة غير متطابقة!',
    'password_min_length': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل!',
    'password_changed_successfully': 'تم تغيير كلمة المرور بنجاح!',
    'failed_to_change_password': 'فشل تغيير كلمة المرور',
    'account_deleted_successfully': 'تم حذف الحساب بنجاح.',
    'failed_to_delete_account': 'فشل حذف الحساب',
    'create_and_manage_packages': 'إنشاء وإدارة باقات المنتجات',
    'enter_package_name': 'أدخل اسم الباقة',
    'enter_package_description': 'أدخل وصف الباقة',
    'select_products': 'اختر المنتجات',
    'selected': 'محدد',
    'update_package': 'تحديث الباقة',
    'product_added_to_package_successfully': 'تمت إضافة المنتج إلى الباقة بنجاح!',
    'failed_to_add_product_to_package': 'فشل إضافة المنتج إلى الباقة',
    'failed_to_remove_product_from_package': 'فشل إزالة المنتج من الباقة',
    'add_to_package': 'إضافة إلى باقة',
    'failed_to_save_package': 'فشل حفظ الباقة',
    'failed_to_delete_package': 'فشل حذف الباقة',
    'product_created_successfully': 'تم إنشاء المنتج بنجاح',
    'product_updated_successfully': 'تم تحديث المنتج بنجاح',
    'product_deleted_successfully': 'تم حذف المنتج بنجاح',
    'failed_to_fetch_package_products': 'فشل جلب منتجات الباقة',
    'please_fill_all_fields_and_select_product': 'يرجى ملء جميع الحقول واختيار منتج واحد على الأقل',
    'product_added_to_category_successfully': 'تمت إضافة المنتج إلى الفئة بنجاح',
    'product_removed_from_category_successfully': 'تمت إزالة المنتج من الفئة بنجاح',
    'failed_to_fetch_category_products': 'فشل جلب منتجات الفئة',
    'tax_updated_successfully': 'تم تحديث الضريبة بنجاح',
    'tax_created_successfully': 'تم إنشاء الضريبة بنجاح',
    'tax_deleted_successfully': 'تم حذف الضريبة بنجاح',
    'failed_to_save_tax': 'فشل حفظ الضريبة',
    'failed_to_delete_tax': 'فشل حذف الضريبة',
    'failed_to_fetch_delivery_fees': 'فشل جلب رسوم التوصيل',
    'no_description': 'لا يوجد وصف',
    'package_name': 'اسم الباقة',
    'image_url': 'رابط الصورة',
    'create_and_organize_categories': 'إنشاء وتنظيم فئات المنتجات',
    'enter_category_name': 'أدخل اسم الفئة',
    'assign_products': 'تعيين المنتجات',
    'uncategorized': 'غير مصنف',
    'update_category': 'تحديث الفئة',
    'please_enter_category_name': 'الرجاء إدخال اسم الفئة',
    'category_already_exists': 'الفئة موجودة بالفعل',
    'confirm_delete_category': 'هل أنت متأكد من حذف هذه الفئة؟',
    'failed_to_save_category': 'فشل حفظ الفئة',
    'view_manage_all_users': 'عرض وإدارة جميع مستخدمي المنصة',
    'all_users': 'جميع المستخدمين',
    'customers': 'العملاء',
    'admins': 'المشرفون',
    'active_users': 'المستخدمون النشطون',
    'loading_users': 'جاري تحميل المستخدمين...',
    'no_users_found': 'لم يتم العثور على مستخدمين',
    'unknown_user': 'مستخدم غير معروف',
    'private': 'خاص',
    'public': 'عام',
    'view_profile': 'عرض الملف الشخصي',
    'actions': 'الإجراءات',
    'status': 'الحالة',
    'confirm_block_user': 'هل أنت متأكد من حظر هذا المستخدم؟',
    'user_blocked_successfully': 'تم حظر المستخدم بنجاح',
    'failed_to_block_user': 'فشل حظر المستخدم',
    'create_and_manage_products': 'إنشاء وإدارة جميع المنتجات',
    'manage_blocked_users_restore_access': 'إدارة المستخدمين المحظورين واستعادة الوصول عند الحاجة',
    'total_blocked': 'إجمالي المحظورين',
    'blocked_this_week': 'المحظورون هذا الأسبوع',
    'blocked_over_30_days': 'المحظورون لأكثر من 30 يوماً',
    'all_users_have_access': 'جميع المستخدمين لديهم حالياً وصول إلى المنصة',
    'confirm_unblock_user_message': 'هل أنت متأكد من إلغاء حظر هذا المستخدم؟',
    'user_unblocked_success_message': 'تم إلغاء حظر المستخدم بنجاح!',
    'failed_to_unblock_user_message': 'فشل إلغاء حظر المستخدم',
    'service_fees_page_title': 'رسوم الخدمة',
    'configure_delivery_service_fees': 'تكوين رسوم التوصيل والخدمة',
    'base_service_fee': 'رسوم الخدمة الأساسية',
    'applied_to_all_orders': 'يُطبق على جميع الطلبات بغض النظر عن الموقع',
    'service_fee_label': 'رسوم الخدمة',
    'save_service_fee': 'حفظ رسوم الخدمة',
    'delivery_locations': 'مواقع التوصيل',
    'set_delivery_fees_for_locations': 'تعيين رسوم التوصيل لمواقع مختلفة',
    'add_location': 'إضافة موقع',
    'loading_location_fees': 'جاري تحميل رسوم المواقع...',
    'no_delivery_locations_configured': 'لم يتم تكوين مواقع التوصيل بعد',
    'delivery_fee_label': 'رسوم التوصيل',
    'fee_calculation_example': 'مثال على حساب الرسوم',
    'product_total': 'إجمالي المنتج',
    'example': 'مثال',
    'edit_location': 'تعديل الموقع',
    'add_new_location': 'إضافة موقع جديد',
    'location_name': 'اسم الموقع',
    'location_name_placeholder': 'مثال: وسط البلد، الضواحي',
    'delivery_fee_amount': 'رسوم التوصيل',
    'update_location': 'تحديث الموقع',
    'please_enter_service_fee': 'الرجاء إدخال رسوم خدمة صالحة',
    'service_fee_updated_successfully': 'تم تحديث رسوم الخدمة بنجاح!',
    'failed_to_save_service_fee': 'فشل حفظ رسوم الخدمة',
    'failed_to_fetch_locations': 'فشل جلب مواقع التوصيل',
    'please_fill_all_fields': 'الرجاء ملء جميع الحقول',
    'location_saved_successfully': 'تم حفظ الموقع بنجاح!',
    'failed_to_save_location_fee': 'فشل حفظ رسوم الموقع',
    'confirm_delete_location': 'هل أنت متأكد من حذف هذا الموقع؟',
    'location_deleted_successfully': 'تم حذف الموقع بنجاح!',
    'failed_to_delete_location': 'فشل حذف الموقع',
    'please_select_payment_method': 'يرجى اختيار طريقة الدفع',
    'please_fill_contact_info': 'يرجى ملء جميع حقول معلومات الاتصال',
    'please_fill_shipping_address': 'يرجى ملء جميع حقول عنوان الشحن',
    'please_fill_card_details': 'يرجى ملء جميع تفاصيل البطاقة',
    'order_placed_successfully': 'تم تقديم الطلب بنجاح!',
    'your_order_accepted': 'تم قبول طلبك',
    'your_order_rejected': 'تم رفض طلبك',
    'view_messages': 'عرض الرسائل',
    'enter_order_details': 'أدخل بريدك الإلكتروني ورقم هاتفك لعرض الرسائل المتعلقة بطلباتك',
    'create_account_to_chat': 'أنشئ حساباً لإرسال الرسائل والدردشة مع الدعم',
    'read_only_mode': 'وضع القراءة فقط',
    'no_messages_found': 'لم يتم العثور على رسائل',
    'failed_to_authenticate': 'فشل التحقق من الهوية',
    'no_messages_yet': 'لا توجد رسائل بعد',
    'messages_will_appear_here': 'ستظهر الرسائل المتعلقة بطلباتك هنا',
    'failed_to_complete_purchase': 'فشل إتمام الشراء',
    'please_login_to_use_chat': 'يرجى تسجيل الدخول لاستخدام الدردشة',
    'please_login_to_chat': 'يرجى تسجيل الدخول لإرسال الرسائل',
    'optional': 'اختياري',
    'category_image': 'صورة الفئة',
  },
  en: {
    // Common
    'back': 'Back',
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'search': 'Search',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'confirm': 'Confirm',
    'close': 'Close',
    'ok': 'OK',
    'confirm_action': 'Confirm Action',
    'are_you_sure': 'Are you sure?',
    'are_you_sure_you_want_to': 'Are you sure you want to {action}?',

    // Navbar
    'makateb_store': 'Makateb Store',
    'search_products': 'Search products...',
    'sign_in': 'Sign In',
    'profile': 'Profile',
    'orders': 'Orders',
    'settings': 'Settings',
    'logout': 'Logout',
    'contact_support': 'Contact Support',
    'admin_menu': 'Admin Menu',
    'wishlist': 'Wishlist',
    'cart': 'Cart',
    'chat': 'Chat',

    // Home/Dashboard
    'welcome_to_makateb_store': 'Welcome to Makateb Store',
    'welcome_description': 'Welcome to Makateb Store! Everything your office needs, all in one place.',
    'products': 'Products',
    'packages': 'Packages',
    'most_searched': 'Most Searched',
    'view_all': 'View All',
    'add_to_cart': 'Add to Cart',
    'add': 'Add',
    'add_to_wishlist': 'Add to Wishlist',
    'out_of_stock': 'Out of Stock',
    'only_left': 'Only',
    'items': 'items',
    'explore_curated_collection': 'Explore our curated collection',

    // Product
    'product_details': 'Product Details',
    'back_to_products': 'Back to Products',
    'category': 'Category',
    'price': 'Price',
    'description': 'Description',
    'quantity': 'Quantity',
    'stock': 'Stock',
    'customer_reviews': 'Customer Reviews',
    'add_review': 'Add Review',
    'rating': 'Rating',
    'comment': 'Comment',
    'submit': 'Submit',

    // Package
    'package_details': 'Package Details',
    'back_to_packages': 'Back to Packages',
    'special_package_deal': 'Special Package Deal',
    'save': 'Save',
    'original_price': 'Original Price',
    'whats_included': "What's Included",
    'add_package_to_cart': 'Add Package to Cart',

    // Cart
    'shopping_cart': 'Shopping Cart',
    'empty_cart': 'Your cart is empty',
    'start_shopping': 'Start Shopping',
    'total': 'Total',
    'checkout': 'Checkout',
    'remove': 'Remove',
    'view_your_cart': 'View Your Cart',

    // Checkout
    'checkout_page': 'Checkout',
    'order_summary': 'Order Summary',
    'subtotal': 'Subtotal',
    'service_fees': 'Service Fees',
    'payment_method': 'Payment Method',
    'cash_on_delivery': 'Cash on Delivery',
    'credit_card': 'Credit Card',
    'complete_purchase': 'Complete Purchase',
    'shipping_address': 'Shipping Address',
    'city': 'City',
    'address': 'Address',
    'phone': 'Phone',

    // Orders
    'order_history': 'Order History',
    'no_orders': 'No orders yet',
    'order_id': 'Order ID',
    'order': 'Order',
    'order_date': 'Order Date',
    'status': 'Status',
    'pending': 'Pending',
    'processing': 'Processing',
    'shipped': 'Shipped',
    'delivered': 'Delivered',
    'cancelled': 'Cancelled',
    'remove_order': 'Remove Order',
    'confirm_remove_order': 'Are you sure you want to remove this order from your history?',
    'order_removed_successfully': 'Order removed successfully',
    'failed_to_remove_order': 'Failed to remove order',

    // Settings
    'settings': 'Settings',
    'basic_information': 'Basic Information',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'email_address': 'Email Address',
    'save_changes': 'Save Changes',
    'saving': 'Saving...',
    'change_password': 'Change Password',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_password': 'Confirm New Password',
    'changing': 'Changing...',
    'danger_zone': 'Danger Zone',
    'delete_account': 'Delete Account',
    'delete_account_warning': 'Once you delete your account, there is no going back. Please be certain.',
    'are_you_sure': 'Are you absolutely sure?',
    'yes_delete': 'Yes, Delete My Account',
    'language': 'Language',
    'select_language': 'Select Language',
    'arabic': 'Arabic',
    'english': 'English',
    'account_required': 'Account Required',
    'account_required_for_orders_support': 'You must create an account to view order history or contact support',
    'continue_shopping': 'Continue Shopping',

    // Profile
    'user_information': 'User Information',
    'edit_information': 'Edit Information',
    'phone': 'Phone',
    'location': 'Location',
    'bio': 'Bio',
    'privacy_settings': 'Privacy Settings',
    'profile_visibility': 'Profile visibility',
    'public': 'Public',
    'private': 'Private',
    'not_provided': 'Not provided',
    'does_not_create_account': 'Does not create account',
    'order_information': 'Order Information',

    // Chat
    'messages': 'Messages',
    'customer_chat': 'Customer Chat',
    'select_user': 'Select a user to start chatting',
    'type_message': 'Type your message...',
    'send': 'Send',
    'no_conversations': 'No conversations',
    'are_you_sure_clear_chat': 'Are you sure you want to clear this chat?',
    'please_select_image_file': 'Please select an image file',
    'failed_to_send_message': 'Failed to send message',
    'failed_to_fetch_conversations': 'Failed to fetch conversations',
    'failed_to_fetch_messages': 'Failed to fetch messages',
    'failed_to_clear_chat': 'Failed to clear chat',
    'chat_cleared_successfully': 'Chat cleared successfully!',
    'search_users': 'Search users...',

    // Search
    'search_page': 'Search',
    'filter': 'Filter',
    'sort_by': 'Sort By',
    'price_range': 'Price Range',
    'min': 'Min',
    'max': 'Max',
    'apply': 'Apply',
    'reset': 'Reset',
    'no_products_found': 'No products found',

    // Admin
    'manage_site': 'Manage Site',
    'manage_users': 'Manage Users',
    'manage_categories': 'Manage Categories',
    'manage_packages': 'Manage Packages',
    'manage_products': 'Manage Products',
    'service_fees': 'Service Fees',
    'blocked_users': 'Blocked Users',
    'customer_chat': 'Customer Chat',

    // Login
    'welcome_back': 'Welcome Back',
    'sign_in_account': 'Sign in to your account',
    'email': 'Email Address',
    'password': 'Password',
    'role': 'Role',
    'select_role': 'Select Role',
    'customer': 'Customer',
    'admin': 'Admin',
    'sign_in': 'Sign In',
    'dont_have_account': "Don't have an account?",
    'sign_up': 'Sign up',
    'continue_as_guest': 'Continue as guest',
    'please_login_to_access_settings': 'Please login to access settings',
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    'shop_now': 'Shop Now',
    'special_package_deals': 'Special Package Deals',
    'categories': 'Categories',
    'all': 'All',
    'all_products': 'All Products',
    'no_search_data': 'No search data available yet',
    'no_packages_available': 'No packages available',
    'no_products_found': 'No products found. Try a different search or category.',
    'adding': 'Adding...',
    'general': 'General',
    'please_login_to_add_items': 'Please login to add items',
    'removed_from_wishlist': 'Removed from wishlist',
    'added_to_wishlist': 'Added to wishlist',
    'added_to_cart': 'Added to cart',
    'failed_to_add_to_cart': 'Failed to add to cart',
    'failed_to_update_wishlist': 'Failed to update wishlist',
    'package_added_to_cart': 'Package added to cart!',
    'failed_to_add_package_to_cart': 'Failed to add package to cart',
    'uncategorized': 'Uncategorized',
    'reviews': 'reviews',
    'no_description_available': 'No description available',
    'all_packages': 'All Packages',
    'showing_all_packages': 'Showing all packages ({count})',
    'off': 'off',
    'only_left_in_stock': 'Only',
    'left_in_stock': 'left in stock!',
    'add_package_to_cart': 'Add Package to Cart',
    'whats_included': "What's Included",
    'no_products_in_package': 'No products found in this package',
    'your_cart_is_empty': 'Your cart is empty',
    'add_some_products': 'Add some beautiful products to get started!',
    'start_shopping': 'Start Shopping',
    'order_summary': 'Order Summary',
    'subtotal': 'Subtotal',
    'shipping': 'Shipping',
    'calculated_at_checkout': 'Calculated at checkout',
    'proceed_to_checkout': 'Proceed to Checkout',
    'remove': 'Remove',
    'please_login_to_view_orders': 'Please login to view your orders',
    'start_shopping_and_orders': 'Start shopping and your orders will appear here!',
    'placed_on': 'Placed on',
    'items_count': 'items',
    'view_details': 'View Details',
    'contact_information': 'Contact Information',
    'full_name': 'Full Name',
    'shipping_address': 'Shipping Address',
    'zip_code': 'ZIP Code',
    'select_location': 'Select Location',
    'payment_method': 'Payment Method',
    'cash_on_delivery': 'Cash on Delivery',
    'credit_card': 'Credit Card',
    'complete_purchase': 'Complete Purchase',
    'customer_chat': 'Customer Chat',
    'search_users': 'Search users...',
    'select_user_to_chat': 'Select a user to start chatting',
    'no_messages': 'No messages',
    'type_your_message': 'Type your message...',
    'send': 'Send',
    'admin_code': 'Admin Code (4 digits)',
    'enter_admin_code': 'Enter admin code',
    'enter_your_password': 'Enter your password',
    'name_example': 'name@example.com',
    'enter_full_name': 'Enter your full name',
    'no_reviews_yet': 'No reviews yet. Be the first to review this product!',
    'write_review': 'Write a Review',
    'anonymous': 'Anonymous',
    'your_review': 'Your Review',
    'share_thoughts': 'Share your thoughts about this product...',
    'submitting': 'Submitting...',
    'submit_review': 'Submit Review',
    'please_login_to_review': 'Please login to submit a review',
    'review_submitted_successfully': 'Review submitted successfully!',
    'failed_to_submit_review': 'Failed to submit review',
    'are_you_sure_delete_comment': 'Are you sure you want to delete this comment?',
    'failed_to_delete_comment': 'Failed to delete comment',
    'processing': 'Processing...',
    'place_order': 'Place Order',
    'agree_terms_conditions': 'By placing your order, you agree to our terms and conditions.',
    'quantity_label': 'Quantity',
    'most_relevant': 'Most Relevant',
    'price_low_to_high': 'Price: Low to High',
    'price_high_to_low': 'Price: High to Low',
    'highest_rated': 'Highest Rated',
    'found': 'Found',
    'for': 'for',
    'try_adjusting_search': 'Try adjusting your search or filters to find what you\'re looking for.',
    'clear_all_filters': 'Clear All Filters',
    'confirm_password': 'Confirm Password',
    'already_have_account': 'Already have an account?',
    'create_account': 'Create Account',
    'card_number': 'Card Number',
    'expiry_date': 'Expiry Date',
    'cvv': 'CVV',
    'please_login_to_view_profile': 'Please login to view your profile',
    'my_profile': 'My Profile',
    'tell_us_about_yourself': 'Tell us about yourself...',
    'no_bio_added': 'No bio added yet.',
    'phone_number': 'Phone Number',
    'phone_placeholder': '+1 234 567 8900',
    'no_phone_added': 'No phone number added.',
    'location_placeholder': 'New York, USA',
    'no_location_added': 'No location added.',
    'private_account': 'Private Account',
    'private_account_description': 'When enabled, only you can see your profile information.',
    'edit_profile': 'Edit Profile',
    'profile_image_updated': 'Profile image updated!',
    'profile_updated_successfully': 'Profile updated successfully!',
    'failed_to_update_profile': 'Failed to update profile',
    'failed_to_update_profile_image': 'Failed to update profile image',
    'category_not_found': 'Category not found',
    'go_to_dashboard': 'Go to Dashboard',
    'no_products_in_category': 'No products in this category',
    'products_in_category': 'Products in Category',
    'add_products': 'Add Products',
    'no_products_available': 'No products available',
    'failed_to_add_product_to_category': 'Failed to add product to category',
    'failed_to_remove_product_from_category': 'Failed to remove product from category',
    'check_back_later': 'Check back later for new products',
    'all_packages': 'All Packages',
    'browse_packages': 'Browse our curated product packages',
    'search_packages': 'Search packages...',
    'latest': 'Latest',
    'name_a_to_z': 'Name: A to Z',
    'name_z_to_a': 'Name: Z to A',
    'products_low_to_high': 'Products: Low to High',
    'products_high_to_low': 'Products: High to Low',
    'wishlist_empty': 'Your wishlist is empty',
    'save_favorite_products': 'Save your favorite products to your wishlist!',
    'browse_products': 'Browse Products',
    'shop_now': 'Shop Now',
    'my_wishlist': 'My Wishlist',
    'view_profile': 'View Profile',
    'clear_chat': 'Clear Chat',
    'block_user': 'Block User',
    'chat_with_user': 'Chat with user',
    'private_profile_message': 'This profile is private. Personal information is not available.',
    'failed_to_block_user': 'Failed to block user',
    'user_profile_updated_successfully': 'User profile updated successfully!',
    'failed_to_update_user_profile': 'Failed to update user profile',
    'failed_to_fetch_customers': 'Failed to fetch customers',
    'failed_to_load_order_data': 'Failed to load order data',
    'failed_to_load_user_data': 'Failed to load user data',
    'user_blocked_successfully': 'User blocked and account deleted successfully',
    'are_you_sure_block_user': 'Are you sure you want to block {name}?',
    'loading_order_details': 'Loading order details...',
    'order_status': 'Order Status',
    'order_items': 'Order Items',
    'price_each': 'Price: {price} JD each',
    'in_stock_available': 'In Stock ({stock} available)',
    'out_of_stock': 'Out of Stock',
    'customer_information': 'Customer Information',
    'name': 'Name',
    'phone': 'Phone',
    'tax': 'Tax',
    'free': 'Free',
    'move_to_cart': 'Move to Cart',
    'adding_to_cart': 'Adding to Cart...',
    'back_to_orders': 'Back to Orders',
    'order_not_found': 'Order not found',
    'no_items_in_order': 'No items in this order',
    'items_moved_to_cart': '{count} item(s) moved to cart!',
    'items_moved_to_cart_wishlist': '{inStock} in-stock item(s) moved to cart. {outOfStock} out-of-stock item(s) added to wishlist.',
    'all_items_out_of_stock': 'All items are out of stock. {count} item(s) added to wishlist.',
    'no_items_could_be_moved': 'No items could be moved to cart.',
    'failed_to_move_to_cart': 'Failed to move items to cart',
    'orders_checkout': 'Orders Checkout',
    'approve_or_reject_payments': 'Approve or reject customer payments',
    'back_to_admin_dashboard': 'Back to Admin Dashboard',
    'pending': 'Pending',
    'total_orders': 'Total Orders',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'guest_user': 'Guest User',
    'hide': 'Hide',
    'view': 'View',
    'service_fee': 'Service Fee',
    'delivery_fee': 'Delivery Fee',
    'reject': 'Reject',
    'approve_payment': 'Approve Payment',
    'payment_approved': 'Payment Approved',
    'payment_rejected': 'Payment Rejected',
    'no_orders_found': 'No Orders Found',
    'no_orders_yet': 'There are no orders yet.',
    'no_orders_with_status': 'There are no {status} orders.',
    'are_you_sure_approve_payment': 'Are you sure you want to approve this payment?',
    'are_you_sure_reject_payment': 'Are you sure you want to reject this payment?',
    'payment_approved_successfully': 'Payment approved successfully!',
    'failed_to_approve_payment': 'Failed to approve payment',
    'failed_to_reject_payment': 'Failed to reject payment',
    'failed_to_fetch_orders': 'Failed to fetch orders',
    'not_specified': 'Not Specified',
    'all_users': 'All Users',
    'active_pages': 'Active Pages',
    'showing_all_products': 'Showing all {count} products in the store',
    'total_registered_users': 'Total of {count} registered users',
    'active_pages_count': '{count} active pages in the application',
    'blocked_users_count': '{count} users currently blocked',
    'details': 'Details',
    'stock': 'Stock',
    'no_users_found': 'No Users Found',
    'no_pages_found': 'No Pages Found',
    'no_blocked_users': 'No Blocked Users',
    'all_users_active': 'All users are currently active.',
    'path': 'Path',
    'last_visit': 'Last visit',
    'total_visits': 'Total Visits',
    'blocked_on': 'Blocked on',
    'unblock_user': 'Unblock User',
    'are_you_sure_unblock_user': 'Are you sure you want to unblock this user?',
    'user_unblocked_successfully': 'User unblocked successfully',
    'failed_to_unblock_user': 'Failed to unblock user',
    'user': 'User',
    'home_page': 'Home Page',
    'products_page': 'Products Page',
    'shopping_cart': 'Shopping Cart',
    'wishlist': 'Wishlist',
    'checkout': 'Checkout',
    'profile_page': 'Profile Page',
    'orders_history': 'Orders History',
    'settings': 'Settings',
    'support_chat': 'Support Chat',
    'search_results': 'Search Results',
    'total_products': 'Total Products',
    'total_users': 'Total Users',
    'active_packages': 'Active Packages',
    'click_to_view_details': 'Click to view details',
    'back_to_home': 'Back to Home',
    'reorder': 'Reorder',
    'order_added_to_cart': '{count} item(s) added to cart!',
    'image_link': 'Image Link',
    'upload_file': 'Upload File',
    'cloudinary': 'Cloudinary',
    'enter_image_url': 'Enter Image URL',
    'image_url_placeholder': 'https://example.com/image.jpg',
    'add_image': 'Add Image',
    'upload_image': 'Upload Image',
    'drag_drop_or_click': 'Drag and drop image here or click to select',
    'supported_formats': 'Supported formats',
    'max_size': 'Max size',
    'browse_files': 'Browse Files',
    'select_from_cloudinary': 'Select from Cloudinary',
    'browse_cloudinary': 'Browse Cloudinary',
    'upload_to_cloudinary': 'Upload to Cloudinary',
    'select_file': 'Select File',
    'drag_drop_or_click_to_upload_cloudinary': 'Drag & drop or click to upload to Cloudinary',
    'selected_image': 'Selected Image',
    'selected_images': 'Selected Images',
    'primary': 'Primary',
    'preview': 'Preview',
    'please_enter_valid_url': 'Please enter a valid URL',
    'file_too_large': 'File is too large (max 5MB)',
    'failed_to_upload_image': 'Failed to upload image',
    'failed_to_load_cloudinary_images': 'Failed to load Cloudinary images',
    'manage_products': 'Manage Products',
    'create_and_manage_products': 'Create and manage all products',
    'welcome_admin_manage_store': 'Welcome, Admin! Manage all aspects of Makateb Store.',
    'create_edit_packages_description': 'Create and modify packages and add/remove products',
    'create_categories_description': 'Create categories and organize products',
    'create_edit_products_description': 'Create and modify products and manage inventory',
    'view_block_manage_users_description': 'View, block, and manage all users',
    'set_delivery_service_fees_description': 'Set delivery and service fees by location',
    'view_manage_blocked_users_description': 'View and manage blocked users',
    'chat_with_customers_realtime_description': 'Chat with customers in real-time',
    'approve_reject_payments_description': 'Approve or reject customer payments',
    'manage_admin_codes': 'Manage Admin Codes',
    'create_manage_admin_codes_description': 'Create and manage admin codes',
    'add_new_admin_code': 'Add New Admin Code',
    'code_must_be_4_digits': 'Code must be exactly 4 digits',
    'adding': 'Adding...',
    'add_code': 'Add Code',
    'admin_codes_list': 'Admin Codes List',
    'no_admin_codes': 'No admin codes',
    'active': 'Active',
    'inactive': 'Inactive',
    'super_admin': 'Super Admin',
    'protected': 'Protected',
    'created_at': 'Created At',
    'deactivate': 'Deactivate',
    'activate': 'Activate',
    'are_you_sure_delete_admin_code': 'Are you sure you want to delete this admin code?',
    'admin_code_added_successfully': 'Admin code added successfully',
    'admin_code_deleted_successfully': 'Admin code deleted successfully',
    'admin_code_updated_successfully': 'Admin code updated successfully',
    'failed_to_fetch_admin_codes': 'Failed to fetch admin codes',
    'failed_to_add_admin_code': 'Failed to add admin code',
    'failed_to_delete_admin_code': 'Failed to delete admin code',
    'failed_to_update_admin_code': 'Failed to update admin code',
    'cannot_delete_super_admin_code': 'Cannot delete super admin code',
    'cannot_modify_super_admin_code': 'Cannot modify super admin code',
    'unauthorized_access': 'Unauthorized access',
    'create_product': 'Create Product',
    'edit_product': 'Edit Product',
    'delete_product': 'Delete Product',
    'product_name': 'Product Name',
    'product_description': 'Product Description',
    'product_price': 'Product Price',
    'product_stock': 'Stock',
    'product_category': 'Category',
    'product_images': 'Product Images (Optional)',
    'add_to_packages': 'Add to Packages',
    'loading_products': 'Loading products...',
    'no_products_found': 'No products found',
    'product_created_successfully': 'Product created successfully',
    'product_updated_successfully': 'Product updated successfully',
    'product_deleted_successfully': 'Product deleted successfully',
    'manage_packages': 'Manage Packages',
    'create_and_manage_packages': 'Create and manage product packages',
    'create_package': 'Create Package',
    'edit_package': 'Edit Package',
    'delete_package': 'Delete Package',
    'package_name': 'Package Name',
    'package_description': 'Package Description',
    'package_price': 'Package Price',
    'package_image': 'Package Image',
    'package_products': 'Package Products',
    'loading_packages': 'Loading packages...',
    'no_packages_found': 'No packages found',
    'package_created_successfully': 'Package created successfully',
    'package_updated_successfully': 'Package updated successfully',
    'package_deleted_successfully': 'Package deleted successfully',
    'failed_to_save_package': 'Failed to save package',
    'failed_to_delete_package': 'Failed to delete package',
    'failed_to_fetch_package_products': 'Failed to fetch package products',
    'please_fill_all_fields_and_select_product': 'Please fill all fields and select at least one product',
    'product_added_to_category_successfully': 'Product added to category successfully',
    'product_removed_from_category_successfully': 'Product removed from category successfully',
    'failed_to_fetch_category_products': 'Failed to fetch category products',
    'tax_updated_successfully': 'Tax updated successfully',
    'tax_created_successfully': 'Tax created successfully',
    'tax_deleted_successfully': 'Tax deleted successfully',
    'failed_to_save_tax': 'Failed to save tax',
    'failed_to_delete_tax': 'Failed to delete tax',
    'failed_to_fetch_delivery_fees': 'Failed to fetch delivery fees',
    'manage_categories': 'Manage Categories',
    'create_and_organize_categories': 'Create and organize product categories',
    'create_category': 'Create Category',
    'edit_category': 'Edit Category',
    'delete_category': 'Delete Category',
    'category_name': 'Category Name',
    'category_image': 'Category Image',
    'loading_categories': 'Loading categories...',
    'no_categories_found': 'No categories found',
    'category_created_successfully': 'Category created successfully',
    'category_updated_successfully': 'Category updated successfully',
    'category_deleted_successfully': 'Category deleted successfully',
    'image_link': 'Image Link',
    'upload_file': 'Upload File',
    'cloudinary': 'Cloudinary',
    'enter_image_url': 'Enter Image URL',
    'image_url_placeholder': 'https://example.com/image.jpg',
    'add_image': 'Add Image',
    'upload_image': 'Upload Image',
    'drag_drop_or_click': 'Drag and drop image here or click to select',
    'supported_formats': 'Supported formats',
    'max_size': 'Max size',
    'browse_files': 'Browse Files',
    'select_from_cloudinary': 'Select from Cloudinary',
    'browse_cloudinary': 'Browse Cloudinary',
    'upload_to_cloudinary': 'Upload to Cloudinary',
    'select_file': 'Select File',
    'drag_drop_or_click_to_upload_cloudinary': 'Drag & drop or click to upload to Cloudinary',
    'selected_image': 'Selected Image',
    'selected_images': 'Selected Images',
    'primary': 'Primary',
    'preview': 'Preview',
    'please_enter_valid_url': 'Please enter a valid URL',
    'file_too_large': 'File is too large (max 5MB)',
    'failed_to_upload_image': 'Failed to upload image',
    'failed_to_load_cloudinary_images': 'Failed to load Cloudinary images',
    'please_enter_first_name': 'Please enter at least a first name',
    'basic_information_updated_successfully': 'Basic information updated successfully!',
    'failed_to_update_profile': 'Failed to update profile',
    'passwords_do_not_match': 'New passwords do not match!',
    'password_min_length': 'Password must be at least 8 characters long!',
    'password_changed_successfully': 'Password changed successfully!',
    'failed_to_change_password': 'Failed to change password',
    'account_deleted_successfully': 'Account deleted successfully.',
    'failed_to_delete_account': 'Failed to delete account',
    'create_and_manage_packages': 'Create and manage product packages',
    'enter_package_name': 'Enter package name',
    'enter_package_description': 'Enter package description',
    'select_products': 'Select Products',
    'selected': 'selected',
    'update_package': 'Update Package',
    'product_added_to_package_successfully': 'Product added to package successfully!',
    'failed_to_add_product_to_package': 'Failed to add product to package',
    'failed_to_remove_product_from_package': 'Failed to remove product from package',
    'add_to_package': 'Add to Package',
    'no_description': 'No description',
    'package_name': 'Package Name',
    'image_url': 'Image URL',
    'enter_category_name': 'Enter category name',
    'assign_products': 'Assign Products',
    'uncategorized': 'Uncategorized',
    'update_category': 'Update Category',
    'please_enter_category_name': 'Please enter a category name',
    'category_already_exists': 'Category already exists',
    'confirm_delete_category': 'Are you sure you want to delete this category?',
    'failed_to_save_category': 'Failed to save category',
    'view_manage_all_users': 'View and manage all platform users',
    'all_users': 'All Users',
    'customers': 'Customers',
    'admins': 'Admins',
    'active_users': 'Active Users',
    'loading_users': 'Loading users...',
    'no_users_found': 'No users found',
    'unknown_user': 'Unknown User',
    'private': 'Private',
    'public': 'Public',
    'view_profile': 'View Profile',
    'actions': 'Actions',
    'status': 'Status',
    'confirm_block_user': 'Are you sure you want to block this user?',
    'user_blocked_successfully': 'User blocked successfully',
    'failed_to_block_user': 'Failed to block user',
    'manage_blocked_users_restore_access': 'Manage blocked users and restore access when needed',
    'total_blocked': 'Total Blocked',
    'blocked_this_week': 'Blocked This Week',
    'blocked_over_30_days': 'Blocked Over 30 Days',
    'all_users_have_access': 'All users currently have access to the platform',
    'confirm_unblock_user_message': 'Are you sure you want to unblock this user?',
    'user_unblocked_success_message': 'User unblocked successfully!',
    'failed_to_unblock_user_message': 'Failed to unblock user',
    'service_fees_page_title': 'Service Fees',
    'configure_delivery_service_fees': 'Configure delivery and service fees',
    'base_service_fee': 'Base Service Fee',
    'applied_to_all_orders': 'Applied to all orders regardless of location',
    'service_fee_label': 'Service Fee',
    'save_service_fee': 'Save Service Fee',
    'delivery_locations': 'Delivery Locations',
    'set_delivery_fees_for_locations': 'Set delivery fees for different locations',
    'add_location': 'Add Location',
    'loading_location_fees': 'Loading location fees...',
    'no_delivery_locations_configured': 'No delivery locations configured yet',
    'delivery_fee_label': 'Delivery Fee',
    'fee_calculation_example': 'Fee Calculation Example',
    'product_total': 'Product Total',
    'example': 'Example',
    'edit_location': 'Edit Location',
    'add_new_location': 'Add New Location',
    'location_name': 'Location Name',
    'location_name_placeholder': 'e.g., Downtown, Suburbs',
    'delivery_fee_amount': 'Delivery Fee',
    'update_location': 'Update Location',
    'please_enter_service_fee': 'Please enter a valid service fee',
    'service_fee_updated_successfully': 'Service fee updated successfully!',
    'failed_to_save_service_fee': 'Failed to save service fee',
    'failed_to_fetch_locations': 'Failed to fetch location fees',
    'please_fill_all_fields': 'Please fill all fields',
    'location_saved_successfully': 'Delivery location saved successfully!',
    'failed_to_save_location_fee': 'Failed to save location fee',
    'confirm_delete_location': 'Are you sure you want to delete this delivery location?',
    'location_deleted_successfully': 'Delivery location deleted successfully!',
    'failed_to_delete_location': 'Failed to delete location fee',
    'please_select_payment_method': 'Please select a payment method',
    'please_fill_contact_info': 'Please fill in all contact information fields',
    'please_fill_shipping_address': 'Please fill in all shipping address fields',
    'please_fill_card_details': 'Please fill in all credit card details',
    'order_placed_successfully': 'Order placed successfully!',
    'your_order_accepted': 'Your order has been accepted',
    'your_order_rejected': 'Your order has been rejected',
    'view_messages': 'View Messages',
    'enter_order_details': 'Enter your email and phone number to view messages about your orders',
    'create_account_to_chat': 'Create an account to send messages and chat with support',
    'read_only_mode': 'Read-only mode',
    'no_messages_found': 'No messages found',
    'failed_to_authenticate': 'Failed to authenticate',
    'no_messages_yet': 'No messages yet',
    'messages_will_appear_here': 'Messages about your orders will appear here',
    'please_login_to_chat': 'Please login to send messages',
    'failed_to_complete_purchase': 'Failed to complete purchase',
    'please_login_to_use_chat': 'Please login to use chat',
    'no_items_in_stock_to_add_to_cart': 'No items in stock to add to cart',
    'added_x_items_to_cart': 'Added {count} item(s) to cart',
    'some_items_could_not_be_added_to_cart': 'Some items could not be added to cart',
    'wishlist_cleared': 'Wishlist cleared',
    'failed_to_delete_product': 'Failed to delete product',
    'please_login_to_update_cart_items': 'Please login to update cart items',
    'please_login_to_remove_cart_items': 'Please login to remove cart items',
    'failed_to_load_package': 'Failed to load package',
    'this_package_has_no_products': 'This package has no products',
    'please_select_an_image_file': 'Please select an image file',
    'please_login_to_contact_support': 'Please login to contact support',
    'no_admins_available_at_the_moment': 'No admins available at the moment',
    'failed_to_connect_to_support': 'Failed to connect to support. Please try again later.',
    'optional': 'Optional',
    'category_image': 'Category Image',
  }
};

export const useLanguageStore = defineStore('language', () => {
  // Default to Arabic
  const currentLanguage = ref(localStorage.getItem('language') || 'ar');

  const t = computed(() => {
    return (key) => {
      return translations[currentLanguage.value]?.[key] || translations['ar'][key] || key;
    };
  });

  // Add translateName functions
  const translateCategoryName = (name) => translateName(name, 'category');
  const translatePackageName = (name) => translateName(name, 'package');

  const setLanguage = (lang) => {
    currentLanguage.value = lang;
    localStorage.setItem('language', lang);
    // Update HTML dir attribute for RTL support
    document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', lang);
    // Update axios language header
    if (typeof window !== 'undefined' && window.axios) {
      window.axios.defaults.headers.common['Accept-Language'] = lang;
    }
  };

  // Helper function to get localized name for categories/packages
  const getLocalizedName = (item) => {
    if (!item) return '';
    const isArabic = currentLanguage.value === 'ar';
    return isArabic
      ? (item.name_ar || item.name_en || item.name || '')
      : (item.name_en || item.name_ar || item.name || '');
  };

  // Helper function to get localized description for products/packages
  const getLocalizedDescription = (item) => {
    if (!item) return '';
    const isArabic = currentLanguage.value === 'ar';
    return isArabic
      ? (item.description_ar || item.description_en || item.description || '')
      : (item.description_en || item.description_ar || item.description || '');
  };

  const isRTL = computed(() => currentLanguage.value === 'ar');

  // Initialize on mount
  if (typeof window !== 'undefined') {
    document.documentElement.setAttribute('dir', currentLanguage.value === 'ar' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', currentLanguage.value);
  }

  return {
    currentLanguage,
    t,
    setLanguage,
    isRTL,
    translateCategoryName,
    translatePackageName,
    getLocalizedName,
    getLocalizedDescription,
  };
});

